### ISSUE TITLE
support / in aliases

### ISSUE THREAD

**Issue by vahidfazelrezai** [rockset/shortlinks#1]
currently / gets converted to -

**Comment by sandeepgd** [comment]
e.g. can't have go/rs/cpp

**Comment by vahidfazelrezai** [comment]
@sandeepgd  go/rs/cpp now works :) 

The change was to make non-alphanumeric characters convert to "-" not just in alias creation, but also in alias redirection.

**Comment by sandeepgd** [comment]
To further improve upon this:
Is it easy to make the go links dynamic by appending the part after / to the target url itself. For example, go/rs/cpp should work even when only go/rs link is created. Then, I could just say go/philacity/D698 and get redirected to the particular changelist.

**Comment by vahidfazelrezai** [comment]
https://github.com/rockset/shortlinks/commit/8695d2ae79fbd1bd46e7560c0acc42540e52c9d0
